spring:
  profiles:
    active:
  application:
    name: gateway

server:
  port: 8102

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "${EUREKA_URI:http://localhost:8101/eureka}"
    instance:
      preferIpAddress: true

zuul:
  routes:
    token-service:
      path: /token/**
      strip-prefix: false
  ignored-services: '*'
  prefix: /api
  host:
    connect-timeout-millis: 1000
    socket-timeout-millis: 1000

dataEditor:
  publicKey: publicKey.pem
---



spring:
  profiles: prod
logging:
  config: Gateway\\src\\main\\resources\\Log4J2\\Log4j2.xml
